export const SIDEBAR_MENU = [
  {
    key: "dashboard",
    type: "item",
    label: "Dashboard",
    path: "/",
    icon: "dashboard",
  },
  {
    key: "platform-admin",
    type: "group",
    label: "Platform Administration",
    access: "platform-admin",
    children: [
      {
        key: "platform-admin-dashboard",
        type: "item",
        label: "Platform Dashboard",
        path: "/platform-admin",
        icon: "dashboard",
        access: "platform-admin",
      },
      {
        key: "platform-admin-features",
        type: "item",
        label: "Features",
        path: "/platform-admin/features",
        icon: "credit-card",
        access: "platform-admin",
      },
      {
        key: "platform-admin-subscription-plans",
        type: "item",
        label: "Subscription Plans",
        path: "/platform-admin/subscription-plans",
        icon: "credit-card",
        access: "platform-admin",
      },
      {
        key: "platform-admin-plan-features",
        type: "item",
        label: "Plan Features",
        path: "/platform-admin/plan-features",
        icon: "credit-card",
        access: "platform-admin",
      },
      {
        key: "accounts",
        type: "item",
        label: "Accounts",
        path: "/accounts",
        icon: "credit-card",
        access: "platform-admin",
      },
      {
        key: "users",
        type: "item",
        label: "Users",
        path: "/users",
        icon: "users",
        access: "platform-admin",
      },
      {
        key: "workspaces",
        type: "item",
        label: "Workspaces",
        path: "/workspaces",
        icon: "users",
      },
      {
        key: "workspace-membebrship",
        type: "item",
        label: "Workspace Membership",
        path: "/workspace-memberships",
        icon: "users",
      },
      {
        key: "companies",
        type: "item",
        label: "Company",
        path: "/companies",
        icon: "users",
      },
      {
        key: "financial-years",
        type: "item",
        label: "Financial Year",
        path: "/financial-years",
        icon: "users",
      },
      {
        key: "number-series",
        type: "item",
        label: "Number  Series",
        path: "/number-series",
        icon: "users",
      },
      {
        key: "branches",
        type: "item",
        label: "Branches",
        path: "/branches",
        icon: "users",
      },
      {
        key: "warehouses",
        type: "item",
        label: "Warehouse",
        path: "/warehouses",
        icon: "users",
      },
       {
        key: "bank-accounts",
        type: "item",
        label: "Bank Accounts",
        path: "/bank-accounts",
        icon: "users",
      },
      {
        key: "units",
        type: "item",
        label: "Units",
        path: "/units",
        icon: "users",
      },
      {
        key: "taxes",
        type: "item",
        label: "Taxes",
        path: "/taxes",
        icon: "users",
      },
      {
        key: "currencies",
        type: "item",
        label: "Currencies",
        path: "/currencies",
        icon: "users",
      },
      {
        key: "payment-terms",
        type: "item",
        label: "Payment Terms",
        path: "/payment-terms",
        icon: "users",
      },
      {
        key: "banks",
        type: "item",
        label: "Banks",
        path: "/banks",
        icon: "users",
      },
      {
        key: "hsn-sac",
        type: "item",
        label: "HSN & SAC",
        path: "/hsn-sac",
        icon: "users",
      },
      {
        key: "partner-categories",
        type: "item",
        label: "Partner Category",
        path: "/partner-categories",
        icon: "users",
      },
      {
        key: "product-categories",
        type: "item",
        label: "Product Category",
        path: "/product-categories",
        icon: "users",
      },
    ],
  },
  {
    key: "masters",
    type: "group",
    label: "Masters",
    children: [
      {
        key: "customers",
        type: "item",
        label: "Customers",
        path: "/customers",
        icon: "customers",
      },
      {
        key: "vendors",
        type: "item",
        label: "Vendors",
        path: "/vendors",
        icon: "vendors",
      },
      {
        key: "products",
        type: "item",
        label: "Products",
        path: "/products",
        icon: "products",
      },
    ],
  },

  {
    key: "sales",
    type: "group",
    label: "Sales",
    children: [
      {
        key: "invoices",
        type: "item",
        label: "Invoices",
        path: "/invoices",
        icon: "invoices",
      },
      {
        key: "sales-orders",
        type: "item",
        label: "Sales Orders",
        path: "/sales-orders",
        icon: "sales",
      },
    ],
  },

  {
    key: "purchase",
    type: "group",
    label: "Purchase",
    children: [
      {
        key: "purchase-orders",
        type: "item",
        label: "Purchase Orders",
        path: "/purchase-orders",
        icon: "purchases",
      },
    ],
  },
];
